# Basic Configuration

baseurl = "http://www.justin-silverman.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

author = "Justin Silverman"
title = "Justin Silverman Homepage"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Justin D. Silverman, MD, PhD"
intro = "Assistant Professor - Penn State University   Founder & Chief Scientist - Anarres Analytics"
description="Statistics, Bioinformatics, Medicine, Agriculture"
authorimage = "Silverman-Justin.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Personal Homepage, Justin D. Silverman"
keywords = "statistics, bioinformatics,  biomedical, multivariate statistics, bayesian statistics, time-series, longitudinal data"

## Social Accounts
[params.social]
github = "jsilve24"
# instagram = "<username>"
# xing = "<username>"
# linkedin = "<username>"
twitter = "inschool4life"
# facebook = "<username>"
# google = "<username>"
googlescholar = "V8RmiSAAAAAJ&hl"
# stackoverflow = "<username>"
# lastfm = "<username>"
# goodreads = "<username>"
# gitlab = "<username>"
# bitbucket = "<username>"
# fivehundredpx = "<username>"
# flickr = "<username>"
# foursquare = "<username>"
# hackernews = "<username>"
# kickstarter = "<username>"
# patreon = "<username>"
# pintrest = "<username>"
# steam = "<username>"
# reddit = "<username>"
# snapchat = "<username>"
# youtube = "<channelid>"
# keybase = "<username>"
# twitch = "<username>"
# soundcloud = "<username>"
# tumblr = "<username>"
# strava = "<username>"
# skype = "<username>"
# telegram = "<username>"
# whatsapp = "<username>"
email = "justinsilverman@psu.edu"
# pgp = "<key_fingerprint>"

## Extras
[params.extra]
copyright = "© 2022. Justin Silverman."
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
[[menu.main]]
    name = "about"
    weight = 100
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "consulting"
    identifier = "statistical consulting"
    weight = 200
    url = "/consulting/"
[[menu.main]]
    name = "lab website"
    weight = 300
    url = "https://jsilve24.github.io/SilvermanLab/"
[[menu.main]]
    name = "blog"
    weight = 400
    url = "http://www.statsathome.com/"
[[menu.main]]
    name = "farming"
    weight = 500
    url="https://jsilve24.github.io/HomewoodFarm/"
# [[menu.main]]
#     name = "teaching"
#     weight = 500
#     url = "http://www.statsathome.com/"
# [[menu.main]]
#     name = "farming"
#     weight = 600
#     url = "http://www.statsathome.com/"



